### ISSUE TITLE
Gui v2 TODO

### ISSUE THREAD

**Issue by lurr** [LunarComputing/LunarComputing#11]
- [ ] Border
  - [X] Border textures
- [ ] Font rendering.
  - [ ] Make an actual font.
- [ ] Colours
  - [ ] Background (bg)
  - [ ] Text (txt)
  - [ ] Text Colour (fg)
- [ ] Packets
  - [ ] Limit packets, and only send to those who have the computer opened.
